### PR TITLE
Fixed downloading of episodes

### PR DESCRIPTION
**Pull request by AnAppleforlife**
Please note that this worked for the videos I tested it on.

If you have anything you might want to add or change fell free to comment or contact me.

### CODE REVIEW

**Comment by flashpc** [comment]
not sure if I'm doing something wrong, but it downloads the video and audio, but doesn't merge them
error
it says there is an issue with the language

**Comment by AnAppleforlife** [comment]
Well yes. I am currently working on the merge if you have set ffmpeg

**Comment by flashpc** [comment]
Ok, thanks for getting the downloads working

**Comment by AnAppleforlife** [comment]
So my problem right now is that ffmpeg is saying that the input audio is corrupted. 
Does anyone have an idea why that could be?

**Comment by flashpc** [comment]
I focibly added the eng tag to track 1 which fixed the language error, which merged the mkv but errors on the metadata. and forced the output filename to be temp, I created a batch file which fixes my setup temporarily

node funi -s 592641 -e 31 --nosubs && mkvmerge.exe --ui-language en --output ^"C:\videos\That Time I Got Reincarnated as a Slime\S02E06 - The Beauty Makes Her Move.mkv^" --language 0:und --track-name 0:Funimation --default-track 0:yes --language 1:eng --default-track 1:yes ^"^(^" ^"C:\videos\temp.mkv^" ^"^)^" --track-order 0:0,0:1 && del "C:\videos\temp.*"

**Comment by AnAppleforlife** [comment]
The thing is I can play the audio file but on every audio file at ~5:07 seems to be some sort of corruption FFmpeg can't handle.

(I didn't try mkvmerge btw)

**Comment by storm134** [comment]
did not work for me. and at 1% video was a 1gb. i even deleted the old folder and started over from start

C:\funimation-downloader-nx-master>node funi.js -s 124389 --dub --nocleanup -e 92 --verbose

=== Funimation Downloader NX 4.8.0-beta.1 ===

[#124389] My Hero Academia (2016)
[0001] My Hero Academia - #01 Izuku Midoriya: Origin (24:36) [HD1080, English, Japanese, Spanish]
[0002] My Hero Academia - #02 What It Takes to Be a Hero (24:39) [HD1080, Japanese, English, Spanish]

[0089] My Hero Academia S5 - #89 All Hands on Deck! Class 1-A (00:23:50) [HD1080, Portuguese, Spanish, Japanese, English]
[0090] My Hero Academia S5 - #90 Vestiges (00:23:49) [HD1080, Spanish, Portuguese, Japanese, English]
[0091] My Hero Academia S5 - #91 Clash! Class A vs. Class B! (00:23:49) [HD1080, English, Japanese]
[0092] My Hero Academia S5 - #92 Make It Happen, Shinso! (00:23:50) [SD540, English, Japanese] (selected)
[0093] My Hero Academia S5 - #93 Operation New Improv Moves (00:23:50) [HD1080, Japanese]
[0094] My Hero Academia S5 - #94 Foresight (00:23:50) [HD1080, Japanese]

[INFO] Selected Episodes: 0092

[INFO] My Hero Academia - S5E92 - Make It Happen, Shinso!
[INFO] Available streams (Non-Encrypted):
[#1441159] Japanese [Simulcast]
[#1462088] English [Simulcast] (selected)
[INFO] Servers available:
        vmfst-api.prd.funimationsvc.com
[INFO] Available qualities:
         1: 234p (329KiB/s)
         2: 360p (544KiB/s)
         3: 432p (931KiB/s)
         4: 432p (1354KiB/s)
         5: 540p (2281KiB/s)
         6: 720p (3220KiB/s)
         7: 720p (4805KiB/s)
         8: 1080p (6049KiB/s)
         9: 1080p (7962KiB/s)
[INFO] Selected layer: 7 (720p) @ vmfst-api.prd.funimationsvc.com
[INFO] Stream URL: https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2274944/b96cac97-32e6-4fa2-90c8-1a81fc3551efstrnv-hl152_streaming_video_1280_720_4500000_index.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjI3NDk0NC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjE5OTg5NDc0fX19XX0_&Signature=NExRAanpmg7fzwf4u3pb481SJ8iFmbEus8mhMDujAhiG3lBNR5txrw-xM20BJgGmDapN~XLT5xBrVmoASkGEt2IcCojo39HeLbshyOl1a4TdbbzqOMTAXCKSp0XeJW9yjbvMrUgUZt-Dxw41i~jmyuRPUTJ8hpzbpWmaESb~7C9GMTpFFx0u2eelaXX2rstCQ4a8UJvzj-CGSCVSxigbH2~Oc8KUDGtylH4awoFauWeJQxd~vN~rn8SYYbkTBbzN7ERFobzOaKtIvcnDJKF7AMVjfzCTy61tfWiYmNvy-52HYdzEp7HaNPWaHhTce3~KbzGJAn2b9SnDvjDPDYtKog__&rt=1430012
[INFO] Output filename: [Funimation] My Hero Academia - 92 [720p].ts
[INFO] Saving stream to «videos\[Funimation] My Hero Academia - 92 [720p].ts»...
[WARN] Part 4: 2 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 9: 2 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 10: 2 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 6: 2 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 7: 2 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 8: 2 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 3: 2 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 5: 2 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 4: 3 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 9: 3 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 10: 3 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[WARN] Part 6: 3 attempt to retrieve data
        ERROR: Timeout awaiting 'request' for 60000ms
[INFO] 10 of 719 parts downloaded [1%] (3h10m25s)
^C
C:\funimation-downloader-nx-master>

**Comment by AnAppleforlife** [comment]
@storm134 It seems like you not using the code from the pull request though.

**Comment by storm134** [comment]
totally right must have been a blonde moment, Haha. video downloads fine. ffmpeg 4.3.2 merges with no error but no audio

**Comment by AnAppleforlife** [comment]
>  but no audio

Well I had audio in the first 5 minutes

**Pull request merged**
