### PR TITLE
mkvmux fix

### PR DESCRIPTION
**Pull request by Nicknakin**
Modified mkvmux array to only add langauge 1 if necessary, empty lang…

### CODE REVIEW

**Comment by izu-co** [comment]
This repository is untainted

**Comment by Nicknakin** [comment]
Meaning you don't accept PRs?

**Comment by izu-co** [comment]
I do but I have no permission on this repo.

**Comment by NatsuFT36** [comment]
Hi, I wish you could add for the server formats from the previous season in Funimation on Cloudfront d33et77evd9bgg.cloudfront.net

**Comment by izu-co** [comment]
Since no recent activity has been taken place, this PR will be closed. 
If you still want to implement your changes, please consider opening a new PR.

**Pull request closed without merging**
