### PR TITLE
Rewrote file download and resolved issues

### PR DESCRIPTION
**Pull request by izu-co**
- The download will now respect the parts and download them as given in the m3u8 file
 - Fixed broken audio files

### CODE REVIEW

**Comment by AnAppleforlife** [comment]
If you want me to change the version as well, just say so.

It would probably be for the best, since the normal beta 1 version isn't working.

**Comment by storm134** [comment]
thanks just to let you know the search function is no longer working. show results but does not list show id

=== Funimation Downloader NX 4.8.0-beta.1 ===

[INFO] Search Results:
[INFO] Total shows found: 1


C:\funimation-downloader-nx-master>node funi.js --search hero

=== Funimation Downloader NX 4.8.0-beta.1 ===

[INFO] Search Results:
[INFO] Total shows found: 12

**Comment by AnAppleforlife** [comment]
Hey @storm134, thanks for the tip. It should be fixed with https://github.com/anidl/funimation-downloader-nx/pull/60/commits/db5a607f7489555c9d64dd21505586a316a9bdbc.

**Comment by AnAppleforlife** [comment]
@anidl While running through the eslint errors, I noticed that proxies are currently not supported. 
Should I try to fix it or remove it or leave it as it is?

**Comment by STRATOS99K** [comment]
Having a problem with Chinese shows, getting track not selected while trying to download Link Click
node funi -s 1456796 -e 1 -q 0 --sub 
or
node funi -s 1456796 -e 1 -q 0 
Will give the same message, "Track not selected"
Also having support for multisubs would be great, only the english subtitle is being downloaded at the moment.
The list of subs for the current season, from what I've seen on funimation (US)
portuguesebrazil_full.vtt
spanishlatinamerica_full.vtt
english_full.vtt

**Comment by STRATOS99K** [comment]
node funi -s 1394901 -e 1 -q 0 --subLang "pt" --sub  --novids --noaudio
It downloads the subtitle correctly, only 1 option can be chosen at time, could it be possible to add ".en" ".es" ".pt" to the converted file, eg: [Funi] Vivy -Fluorite Eye's Song- - 01 [1080p].en.ass
and for the vttconvert module instead of 'Title: English', having 'Title: ', would make the converter language agnostic

**Comment by XxUnkn0wnxX** [comment]
is this ever going to be merged into the main build? @anidl 
any updates done to the main branch usually only happens once every 2-3 months.

atm main build can only download & not mux the files

**Comment by izu-co** [comment]
Well you can't use the downloader at all, since it's not downloading the parts but the whole video like 720 times.

I published a fixed build on my fork atm.

**Comment by Oujiii** [comment]
Quick question: What does passing `-q` do? Thank you for everything!

**Comment by izu-co** [comment]
@Oujiii  It sets the quality. You can think of it as an ordered list (e.g. 360p, 440p, 720p, 1080p) and you select the number (1-10) which quality should be downloaded. Passing 0 will set it to best.

**Pull request closed without merging**
